"""Open Simple Agent Control Plane backend."""

from osa.control_plane.backend.agent_catalog import (
    AgentCatalog,
    AgentCatalogError,
    AgentRecord,
    AgentRecordStatus,
    AgentVersion,
    ConcurrentUpdateError,
    DuplicateAgentError,
    DuplicateVersionError,
    InvalidTransitionError,
)
from osa.control_plane.backend.deployment import (
    Deployment,
    DeploymentProvider,
    DeploymentSpec,
    DeploymentStatus,
    LocalDeploymentProvider,
)
from osa.control_plane.backend.kubernetes_deployment import (
    KubectlError,
    KubernetesDeploymentProvider,
    KubernetesSecretRef,
)
from osa.control_plane.backend.repositories import (
    AgentRepository,
    AuditEvent,
    AuditEventRepository,
    DeploymentRecord,
    DeploymentRecordRepository,
    InMemoryAgentRepository,
    InMemoryAuditEventRepository,
    InMemoryDeploymentRecordRepository,
    InMemoryResourceDefinitionRepository,
    PostgresAgentRepository,
    PostgresAuditEventRepository,
    PostgresResourceDefinitionRepository,
    ResourceDefinitionRepository,
)
from osa.control_plane.backend.resource_catalogs import ResourceCatalogs
from osa.control_plane.backend.templates import (
    GENERIC_TEMPLATE,
    RESEARCH_TEMPLATE,
    SUPPORT_TEMPLATE,
    AgentTemplate,
    TemplateCatalog,
    create_default_template_catalog,
)

__all__ = [
    "AgentCatalog",
    "AgentCatalogError",
    "AgentRecord",
    "AgentRecordStatus",
    "DuplicateAgentError",
    "DuplicateVersionError",
    "InvalidTransitionError",
    "AgentTemplate",
    "AgentRepository",
    "AgentVersion",
    "AuditEvent",
    "AuditEventRepository",
    "ConcurrentUpdateError",
    "Deployment",
    "DeploymentRecord",
    "DeploymentRecordRepository",
    "DeploymentProvider",
    "DeploymentSpec",
    "DeploymentStatus",
    "GENERIC_TEMPLATE",
    "InMemoryAgentRepository",
    "InMemoryAuditEventRepository",
    "InMemoryDeploymentRecordRepository",
    "InMemoryResourceDefinitionRepository",
    "KubernetesDeploymentProvider",
    "KubernetesSecretRef",
    "KubectlError",
    "RESEARCH_TEMPLATE",
    "LocalDeploymentProvider",
    "PostgresAgentRepository",
    "PostgresAuditEventRepository",
    "PostgresResourceDefinitionRepository",
    "ResourceCatalogs",
    "ResourceDefinitionRepository",
    "SUPPORT_TEMPLATE",
    "TemplateCatalog",
    "create_default_template_catalog",
]
