"""Open Simple Agent domain model and runtime contracts."""

from osa.generic_agent.agent import AbstractAgent, Agent
from osa.generic_agent.agent_capabilities import AgentCapabilities
from osa.generic_agent.agent_id import AgentId
from osa.generic_agent.agent_metadata import AgentMetadata
from osa.generic_agent.agent_request import AgentRequest
from osa.generic_agent.agent_response import AgentResponse
from osa.generic_agent.agent_status import AgentStatus
from osa.generic_agent.audit import AuditEvent, AuditEventSink, InMemoryAuditEventSink
from osa.generic_agent.auth import (
    AuthenticatedPrincipal,
    AuthenticationError,
    AuthMode,
    AuthorizationError,
    AuthorizationPolicy,
    AuthPermission,
    AuthSettings,
    JwksClient,
    JwtAuthenticator,
    OidcDiscoveryClient,
)
from osa.generic_agent.bundle import (
    API_VERSION,
    BUNDLE_KIND,
    BundleCatalogs,
    BundleError,
    BundleMetadata,
    DeploymentBundle,
    DuplicateResourceError,
    InvalidBundleError,
    UnknownReferenceError,
    build_catalogs,
    collect_secret_references,
    load_bundle,
    parse_resource_document,
)
from osa.generic_agent.config import (
    SUPPORTED_API_VERSION,
    SUPPORTED_KIND,
    A2AConfig,
    AccessRule,
    AgentDefinition,
    AgentMetadataConfig,
    AgentSpec,
    ApiKeyCredential,
    ConfigurationError,
    McpRef,
    MemoryConfig,
    MemoryScope,
    ModelRef,
    MtlsCredential,
    OAuth2Credential,
    OutboundCredential,
    ResourcePolicy,
    RuntimeConfig,
    SecretReference,
    SessionConfig,
    SkillRef,
    StrictModel,
    ToolRef,
    load_agent_definition,
)
from osa.generic_agent.credentials import (
    CredentialResolutionError,
    ResolvedOutboundCredential,
    credential_secret_references,
    resolve_outbound_credential,
)
from osa.generic_agent.errors import (
    InvocationTimeoutError,
    IterationLimitExceededError,
    MemoryConfigurationError,
    ModelConfigurationError,
    ModelInvocationError,
    OsaError,
    PolicyViolationError,
    error_payload,
)
from osa.generic_agent.example_tools import CalculatorTool
from osa.generic_agent.mcp import (
    McpCatalog,
    McpConnectionOptions,
    McpDefinition,
    McpPromptMetadata,
    McpResourceMetadata,
    McpToolMetadata,
    McpTransport,
)
from osa.generic_agent.memory import (
    APPLICATION_SCOPE_ID,
    InMemoryProvider,
    MemoryEntry,
    MemoryPolicy,
    MemoryPolicyCatalog,
    MemoryProvider,
    memory_scope_id,
)
from osa.generic_agent.model import ModelCapabilities, ModelCatalog, ModelDefinition, ModelRuntimeSettings
from osa.generic_agent.model_provider import FakeModelProvider, ModelProvider, ModelResponse, TokenUsage
from osa.generic_agent.runtime import AgentFactory, AgentRuntime
from osa.generic_agent.secret import (
    EnvironmentSecretResolver,
    SecretError,
    SecretResolutionError,
    SecretResolver,
    SecretSourceError,
)
from osa.generic_agent.session import (
    Session,
    SessionAccessError,
    SessionError,
    SessionId,
    SessionManager,
    SessionNotFoundError,
    SessionProvider,
)
from osa.generic_agent.skill import SkillCatalog, SkillDefinition
from osa.generic_agent.tool import (
    Tool,
    ToolCapability,
    ToolCatalog,
    ToolCategory,
    ToolDefinition,
    ToolError,
    ToolResult,
    ToolTimeoutError,
)

__all__ = [
    "A2AConfig",
    "ApiKeyCredential",
    "AccessRule",
    "AuditEvent",
    "AuditEventSink",
    "API_VERSION",
    "AbstractAgent",
    "Agent",
    "AgentCapabilities",
    "AgentDefinition",
    "AgentFactory",
    "AgentId",
    "AgentMetadata",
    "AgentMetadataConfig",
    "AgentRequest",
    "AgentResponse",
    "AgentRuntime",
    "AgentSpec",
    "AgentStatus",
    "AuthMode",
    "AuthSettings",
    "AuthenticatedPrincipal",
    "AuthenticationError",
    "AuthorizationError",
    "AuthorizationPolicy",
    "AuthPermission",
    "BUNDLE_KIND",
    "BundleCatalogs",
    "BundleError",
    "BundleMetadata",
    "CalculatorTool",
    "ConfigurationError",
    "DeploymentBundle",
    "DuplicateResourceError",
    "EnvironmentSecretResolver",
    "FakeModelProvider",
    "InMemoryProvider",
    "InMemoryAuditEventSink",
    "InvalidBundleError",
    "InvocationTimeoutError",
    "IterationLimitExceededError",
    "JwksClient",
    "JwtAuthenticator",
    "OidcDiscoveryClient",
    "McpCatalog",
    "McpConnectionOptions",
    "McpDefinition",
    "McpPromptMetadata",
    "McpRef",
    "McpResourceMetadata",
    "McpToolMetadata",
    "McpTransport",
    "MemoryConfig",
    "MemoryEntry",
    "APPLICATION_SCOPE_ID",
    "MemoryConfigurationError",
    "MemoryPolicy",
    "MemoryPolicyCatalog",
    "memory_scope_id",
    "MemoryProvider",
    "MemoryScope",
    "ModelCapabilities",
    "ModelCatalog",
    "ModelConfigurationError",
    "ModelDefinition",
    "ModelInvocationError",
    "ModelProvider",
    "ModelRef",
    "MtlsCredential",
    "OAuth2Credential",
    "OutboundCredential",
    "ModelResponse",
    "ModelRuntimeSettings",
    "OsaError",
    "PolicyViolationError",
    "RuntimeConfig",
    "ResourcePolicy",
    "SUPPORTED_API_VERSION",
    "SUPPORTED_KIND",
    "SecretError",
    "SecretReference",
    "SecretResolutionError",
    "SecretResolver",
    "SecretSourceError",
    "CredentialResolutionError",
    "ResolvedOutboundCredential",
    "credential_secret_references",
    "resolve_outbound_credential",
    "Session",
    "SessionAccessError",
    "SessionConfig",
    "SessionError",
    "SessionId",
    "SessionManager",
    "SessionNotFoundError",
    "SessionProvider",
    "SkillCatalog",
    "SkillDefinition",
    "SkillRef",
    "StrictModel",
    "TokenUsage",
    "Tool",
    "ToolCapability",
    "ToolCatalog",
    "ToolCategory",
    "ToolDefinition",
    "ToolError",
    "ToolRef",
    "ToolResult",
    "ToolTimeoutError",
    "error_payload",
    "UnknownReferenceError",
    "build_catalogs",
    "parse_resource_document",
    "collect_secret_references",
    "load_agent_definition",
    "load_bundle",
]
